services:
  coturn:
    image: coturn/coturn:4.6.3
    container_name: naptin-coturn
    restart: unless-stopped
    command: ["-c", "/etc/coturn/turnserver.conf"]
    network_mode: host
    volumes:
      - ./coturn.turnserver.conf:/etc/coturn/turnserver.conf:ro
