// Server-specific mock data that matches the database schema

export const mockAssets = [
  {
    id: 1,
    assetId: "AST-0001",
    name: "Port Harcourt Refinery Unit 1",
    type: "Refinery Unit",
    location: "Port Harcourt, Rivers State",
    status: "operational",
    criticality: "high",
    latitude: 4.8156,
    longitude: 7.0498,
    manufacturer: "Siemens",
    model: "S7-1500",
    serialNumber: "PH-REF-001-2024",
    installationDate: "2024-01-15",
    lastMaintenance: "2024-06-15",
    nextMaintenance: "2024-07-15",
    department: "Refinery Operations",
    cost: 50000000,
    condition: "excellent",
    locationDetails: "Main refinery complex, Unit 1",
    specifications: {
      capacity: "100,000 bpd",
      pressure: "1500 psi",
      temperature: "350°C"
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 2,
    assetId: "AST-0002",
    name: "Kaduna Refinery Pump Station",
    type: "Pump Station",
    location: "Kaduna, Kaduna State",
    status: "operational",
    criticality: "medium",
    latitude: 10.5222,
    longitude: 7.4384,
    manufacturer: "Atlas Copco",
    model: "GA-110",
    serialNumber: "KD-PUMP-002-2024",
    installationDate: "2024-02-20",
    lastMaintenance: "2024-05-10",
    nextMaintenance: "2024-08-10",
    department: "Pipeline Operations",
    cost: 25000000,
    condition: "good",
    locationDetails: "Pipeline junction, Pump Station A",
    specifications: {
      flowRate: "5000 L/min",
      pressure: "800 psi",
      power: "110 kW"
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 3,
    assetId: "AST-0003",
    name: "Warri Refinery Control System",
    type: "Control System",
    location: "Warri, Delta State",
    status: "maintenance",
    criticality: "high",
    latitude: 5.5560,
    longitude: 5.7847,
    manufacturer: "Honeywell",
    model: "Experion PKS",
    serialNumber: "WR-CS-003-2024",
    installationDate: "2024-03-10",
    lastMaintenance: "2024-06-20",
    nextMaintenance: "2024-09-20",
    department: "Control Systems",
    cost: 35000000,
    condition: "good",
    locationDetails: "Control room, Main building",
    specifications: {
      ioTags: 5000,
      redundancy: "2x2",
      uptime: "99.9%"
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  }
];

export const mockWorkOrders = [
  {
    id: 1,
    workOrderId: "WO-2024-001",
    title: "Preventive Maintenance - Port Harcourt Refinery",
    description: "Monthly preventive maintenance including filter replacement and performance testing",
    type: "preventive",
    priority: "medium",
    status: "completed",
    assignedTo: "John Smith",
    assignedBy: "Maintenance Manager",
    assetId: "AST-0001",
    assetName: "Port Harcourt Refinery Unit 1",
    location: "Port Harcourt, Rivers State",
    estimatedHours: 24,
    actualHours: 22,
    estimatedCost: 50000,
    actualCost: 48000,
    scheduledDate: "2024-06-15",
    startDate: "2024-06-15",
    completionDate: "2024-06-16",
    notes: "Completed successfully with minor adjustments",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 2,
    workOrderId: "WO-2024-002",
    title: "Emergency Repair - Kaduna Pump Station",
    description: "Emergency repair of pump bearing failure",
    type: "corrective",
    priority: "high",
    status: "in-progress",
    assignedTo: "Mike Johnson",
    assignedBy: "Operations Manager",
    assetId: "AST-0002",
    assetName: "Kaduna Refinery Pump Station",
    location: "Kaduna, Kaduna State",
    estimatedHours: 16,
    actualHours: 8,
    estimatedCost: 25000,
    actualCost: 12000,
    scheduledDate: "2024-07-10",
    startDate: "2024-07-10",
    completionDate: null,
    notes: "Bearing replacement in progress",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  }
];

export const mockMaintenanceSchedules = [
  {
    id: 1,
    scheduleId: "MS-2024-001",
    assetId: "AST-0001",
    assetName: "Port Harcourt Refinery Unit 1",
    type: "preventive",
    frequency: "monthly",
    interval: 1,
    lastPerformed: "2024-06-15",
    nextDue: "2024-07-15",
    estimatedDuration: 24,
    estimatedCost: 50000,
    assignedTechnician: "John Smith",
    status: "active",
    description: "Monthly preventive maintenance including filter replacement and performance testing",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 2,
    scheduleId: "MS-2024-002",
    assetId: "AST-0002",
    assetName: "Kaduna Refinery Pump Station",
    type: "preventive",
    frequency: "quarterly",
    interval: 3,
    lastPerformed: "2024-04-10",
    nextDue: "2024-07-10",
    estimatedDuration: 16,
    estimatedCost: 25000,
    assignedTechnician: "Mike Johnson",
    status: "active",
    description: "Quarterly pump maintenance and calibration",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  }
];

export const mockInventory = [
  {
    id: 1,
    itemId: "INV-001",
    name: "High Pressure Pump Bearing",
    description: "SKF 6318-2RS1 bearing for high pressure pumps",
    category: "Bearings",
    subcategory: "Pump Bearings",
    manufacturer: "SKF",
    partNumber: "6318-2RS1",
    unit: "piece",
    currentStock: 15,
    minStock: 5,
    maxStock: 50,
    unitCost: 250,
    totalValue: 3750,
    location: "Main Warehouse",
    shelf: "A-15",
    bin: "B-03",
    supplier: "SKF Nigeria",
    lastOrderDate: "2024-06-15",
    leadTime: 14,
    status: "in-stock",
    condition: "new",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 2,
    itemId: "INV-002",
    name: "Pipeline Valve Actuator",
    description: "Electric actuator for 12-inch pipeline valves",
    category: "Valves",
    subcategory: "Actuators",
    manufacturer: "Rotork",
    partNumber: "IQT-12-24V",
    unit: "piece",
    currentStock: 3,
    minStock: 2,
    maxStock: 10,
    unitCost: 8500,
    totalValue: 25500,
    location: "Main Warehouse",
    shelf: "B-08",
    bin: "C-12",
    supplier: "Rotork Africa",
    lastOrderDate: "2024-05-20",
    leadTime: 21,
    status: "low-stock",
    condition: "new",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 3,
    itemId: "INV-003",
    name: "Refinery Heat Exchanger Tubes",
    description: "Stainless steel tubes for heat exchangers",
    category: "Heat Exchangers",
    subcategory: "Tubes",
    manufacturer: "Tubular Solutions",
    partNumber: "SS-304-25mm",
    unit: "meter",
    currentStock: 200,
    minStock: 100,
    maxStock: 500,
    unitCost: 45,
    totalValue: 9000,
    location: "Main Warehouse",
    shelf: "C-22",
    bin: "D-05",
    supplier: "Tubular Solutions Ltd",
    lastOrderDate: "2024-06-10",
    leadTime: 7,
    status: "in-stock",
    condition: "new",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 4,
    itemId: "INV-004",
    name: "Compressor Oil Filter",
    description: "High efficiency oil filter for Atlas Copco compressors",
    category: "Filters",
    subcategory: "Oil Filters",
    manufacturer: "Atlas Copco",
    partNumber: "OF-110-AC",
    unit: "piece",
    currentStock: 0,
    minStock: 10,
    maxStock: 30,
    unitCost: 180,
    totalValue: 0,
    location: "Main Warehouse",
    shelf: "A-05",
    bin: "B-08",
    supplier: "Atlas Copco Nigeria",
    lastOrderDate: "2024-07-01",
    leadTime: 10,
    status: "out-of-stock",
    condition: "new",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  },
  {
    id: 5,
    itemId: "INV-005",
    name: "Storage Tank Level Sensor",
    description: "Ultrasonic level sensor for storage tanks",
    category: "Sensors",
    subcategory: "Level Sensors",
    manufacturer: "Endress+Hauser",
    partNumber: "FMR-20",
    unit: "piece",
    currentStock: 8,
    minStock: 3,
    maxStock: 15,
    unitCost: 3200,
    totalValue: 25600,
    location: "Main Warehouse",
    shelf: "D-12",
    bin: "E-03",
    supplier: "Endress+Hauser Nigeria",
    lastOrderDate: "2024-06-25",
    leadTime: 14,
    status: "in-stock",
    condition: "new",
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1752146292132"
  }
]; 